project/Clase/urls.py
from django.urls import path

from . import views

app_name = 'clase'

urlpatterns = [
    path('', views.home, name='home'),
    path('curso/create/', views.curso_create, name='curso_create'),
    path('comision/create/', views.comision_create, name='comision_create'),
    path('curso_list/', views.curso_list, name='curso_list'),
    path('estudiantes/', views.estudiantes_list, name='estudiantes_list'),
    path('estudiantes/create', views.estudiantes_create, name='estudiantes_create'),
    path('estudiantes/detail/<int:pk>', views.estudiantes_detail, name='estudiantes_detail'),
    path('profesores/', views.profesores_list, name='profesores_list'),
    path('profesores/create', views.profesores_create, name='profesores_create'),
]

project/config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('clase/', include('clase.urls')),
]

project/core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
]

project/Clase/models.py
from django.db import models

# Modelos creados
class Curso(models.Model):
    """Definicion de Cursos"""
    nombre = models.CharField(max_length=100)
    cant_max_alumnos = models.PositiveBigIntegerField(default=1000, null=True, blank=True, verbose_name="Cantidad máxima de alumnos")

    def __str__(self) -> str:
        return self.nombre
    
    class Meta:
        verbose_name = "Nombre del Curso"
        verbose_name_plural = "Nombres del Curso"

class Estudiante(models.Model):
    """Definicion de clase Estudiantes"""
    nombre = models.CharField(max_length=200)
    apellido = models.CharField(max_length=200, default='')
    cedula_de_identidad = models.CharField(max_length=15, default='')
    email = models.EmailField(max_length=254, default='')
    pais = models.CharField(max_length=50, default='')
    formacion_academica = models.CharField(max_length=200, default='')

    def __str__(self) -> str:
        """Representa una instancia del modelo como una cadena de texto"""
        return f"{self.nombre} {self.apellido}"

class Profesor(models.Model):
    """Definicion de clase Profesores"""
    nombre = models.CharField(max_length=200)
    apellido = models.CharField(max_length=200, default='')
    cedula_de_identidad = models.CharField(max_length=15, default='')
    email = models.EmailField(max_length=254, default='')
    pais = models.CharField(max_length=50, default='')
    profesion = models.CharField(max_length=200, default='')

    def __str__(self) -> str:
        """Representa una instancia del modelo como una cadena de texto"""
        return f"{self.nombre} {self.apellido}"
    
class Comision(models.Model):
    """Definicion de Comisiones"""
    nombre = models.PositiveBigIntegerField(unique=True)
    curso = models.ForeignKey(Curso, on_delete=models.SET_NULL, null=True, blank=True)
    estudiante = models.ManyToManyField(Estudiante)
    profesor = models.ForeignKey(Profesor, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self) -> str:
        """Representa una instancia del modelo como una cadena de texto"""
        return str(self.nombre)

project/Clase/forms.py
from django import forms
from . import models
from .models import Curso, Profesor

class CursoForm(forms.ModelForm):
    class Meta:
        model = models.Curso
        fields = "__all__"
        widgets = {
            "nombre": forms.TextInput(attrs={"class": "form-control"}),
            "cant_max_alumnos": forms.TextInput(attrs={"class": "form-control"}),
        }

class EstudianteForm(forms.ModelForm):
    class Meta:
        model = models.Estudiante
        fields = "__all__"
        widgets = {
            "nombre": forms.TextInput(attrs={"class": "form-control"}),
            "apellido": forms.TextInput(attrs={"class": "form-control"}),
            "cedula_de_identidad": forms.TextInput(attrs={"class": "form-control"}),
            "email": forms.TextInput(attrs={"class": "form-control"}),
            "pais": forms.TextInput(attrs={"class": "form-control"}),
            "formacion_academica": forms.TextInput(attrs={"class": "form-control"}),  
        }

class ProfesorForm(forms.ModelForm):
    class Meta:
        model = models.Profesor
        fields = "__all__"
        widgets = {
            "nombre": forms.TextInput(attrs={"class": "form-control"}),
            "apellido": forms.TextInput(attrs={"class": "form-control"}),
            "cedula_de_identidad": forms.TextInput(attrs={"class": "form-control"}),
            "email": forms.TextInput(attrs={"class": "form-control"}),
            "pais": forms.TextInput(attrs={"class": "form-control"}),
            "profesion": forms.TextInput(attrs={"class": "form-control"}),  
        }

class ComisionForm(forms.ModelForm):
    class Meta:
        model = models.Comision
        fields = "__all__"
        widgets = {
            "nombre": forms.TextInput(attrs={"class": "form-control"}),
            "curso": forms.Select(attrs={"class": "form-control"}),
            "estudiante": forms.SelectMultiple(attrs={"class": "form-control"}),
            "profesor": forms.Select(attrs={"class": "form-control"}),          
        }
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Obtener las opciones disponibles para el campo "curso"
        cursos = Curso.objects.all()
        # Obtener las opciones disponibles para el campo "profesor"
        profesores = Profesor.objects.all()
        # Asignar las opciones al widget correspondiente
        self.fields["curso"].queryset = cursos
        self.fields["profesor"].queryset = profesores

project/Clase/views.py
from django.shortcuts import render, redirect, get_object_or_404
from . import models, forms
from .models import Curso, Comision, Estudiante, Profesor

# Creamos el home
def home(request):
    consulta = request.GET.get("consulta", None)
    form = forms.ComisionForm()
    if consulta:
        print(consulta)
        query = models.Comision.objects.filter(nombre__icontains=consulta)
    else:
        query = models.Comision.objects.all()
    context = {"comisiones": query, "form": form} #consulta a la bdd
    return render(request, "clase/index.html", context)

def comision_create(request):
    if request.method == "POST":
        form = forms.ComisionForm(request.POST)
        if form.is_valid():
            form.save()
            print("Formulario válido")
            return redirect("clase:home")
        else:
            print("Algun dato está mal")
    else:  # request.method == "GET"
        form = forms.ComisionForm()
    return render(request, "clase/comision_create.html", {"form": form})

def curso_list(request):
    cursos = Curso.objects.all()
    form = forms.CursoForm()
    return render(request, 'clase/curso_list.html', {"form": form, "cursos": cursos})

def curso_create(request):
    if request.method == "POST":
        form = forms.CursoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("clase:curso_list")
    else:  # request.method == "GET"
        form = forms.CursoForm()
    return render(request, "clase/curso_list.html", {"form": form})

def estudiantes_list(request):
    consulta = request.GET.get("consulta", None)
    if consulta:
        estudiantes = Estudiante.objects.filter(nombre__icontains=consulta)
    else:
        estudiantes = Estudiante.objects.all()
    form = forms.EstudianteForm()
    return render(request, 'clase/estudiantes_list.html', context={"form": form, 'estudiantes': estudiantes})

def estudiantes_create(request):
    if request.method == "POST":
        form = forms.EstudianteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("clase:estudiantes_list")
    else:  # request.method == "GET"
        form = forms.EstudianteForm()
    return render(request, "clase/estudiantes_list.html", {"form": form})

def estudiantes_detail(request, pk: int):
    estudiante = models.Estudiante.objects.get(id=pk)
    return render(request, "clase/estudiantes_detail.html", {"estudiante": estudiante})

def profesores_list(request):
    consulta = request.GET.get("consulta", None)
    if consulta:
        profesores = Profesor.objects.filter(nombre__icontains=consulta)
    else:
        profesores = Profesor.objects.all()
    form = forms.ProfesorForm()
    return render(request, 'clase/profesores_list.html', context={"form": form, 'profesores': profesores})

def profesores_create(request):
    if request.method == "POST":
        form = forms.ProfesorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("clase:profesores_list")
    else:  # request.method == "GET"
        form = forms.ProfesorForm()
    return render(request, "clase/profesores_list.html", {"form": form})

project/Clase/templates/Clase/comision_create.html
{% extends 'core/base.html' %}

{% block titulo %}
    Lista de Comisiones: Creación
{% endblock titulo %}

{% block contenido %}

    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <button type="submit" class="btn btn-primary">Guardar</button>
    </form>

{% endblock contenido %}

project/Clase/templates/Clase/curso_create.html
{% extends 'core/base.html' %}

{% block titulo %}
    Lista de Cursos: Creación
{% endblock titulo %}

{% block contenido %}
    
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <button type="submit" class="btn btn-primary">Guardar</button>
    </form>

{% endblock contenido %}

project/Clase/templates/Clase/curso_list.html
{% extends 'core/base.html' %}

{% block title %}
    <h1 style="color: blue; font-weight: bold; font-size: 24px; text-decoration: underline;">Listado de Cursos</h1>
{% endblock title %}

{% block content %}
    <div>
        <select name="curso" id="curso">
            {% for curso in cursos %}
                <option value="{{ curso.id }}">{{ curso.nombre }}</option>
            {% endfor %}
        </select>
    </div>
    <div style="margin-top: 60px;" class="py-lg-4">
        <h2>Ingresar Curso</h2>
    </div>
    <form action="{% url 'clase:curso_create' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar</button>
    </form>
    
{% endblock content %}

project/Clase/templates/Clase/estudiantes_create.html
{% extends 'core/base.html' %}

{% block titulo %}
    Alta de Estudiantes
{% endblock titulo %}

{% block contenido %}
    
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <button type="submit" class="btn btn-primary">Guardar</button>
    </form>

{% endblock contenido %}

project/Clase/templates/Clase/estudiantes_detail.html
{% block titulo %}
    Estudiante: +Info
{% endblock titulo %}
{% block contenido %}
    {% if estudiante %}
        <ul>
            <li>Nombre: {{ estudiante.nombre }}</li>
            <li>Apellido: {{ estudiante.apellido }}</li>
            <li>Cédula de Identidad: {{ estudiante.cedula_de_identidad }}</li>
            <li>Email: {{ estudiante.email }}</li>
            <li>País: {{ estudiante.pais }}</li>
            <li>Formación Académica: {{ estudiante.formacion_academica }}</li>
        </ul>
    {% else %}
        <p>No se encontraron datos para este estudiante.</p>
    {% endif %}
    <div class="fs-3 pb-4">
        <a href="{% url 'clase:estudiantes_list' %}">Volver</a>
    </div>
{% endblock contenido %}

project/Clase/templates/Clase/estudiantes_list.html
{% extends 'core/base.html' %}

{% block title %}
    <h1 style="color: blue; font-weight: bold; font-size: 24px; text-decoration: underline;">Listado de Estudiantes</h1>
{% endblock title %}

{% block content %}
    <div class="py-lg-4">
        <form action="{% url 'clase:estudiantes_list' %}" method="get">
            <input type="text" name="consulta" placeholder="Buscar estudiantes...">
            <button type="submit">Buscar</button>
        </form>
    </div>
    <ul>
        {% for estudiante in estudiantes %}
            <li>{{ estudiante.nombre }} {{ estudiante.apellido }}
                <a href="{% url 'clase:estudiantes_detail' estudiante.id %}">Detalle</a>
            </li>
        {% endfor %}
    </ul>
    <div style="margin-top: 60px;" class="py-lg-4">
        <h2>Ingresar Estudiante</h2>
    </div>
    <form action="{% url 'clase:estudiantes_create' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar</button>
    </form>
{% endblock content %}

project/Clase/templates/Clase/index.html
{% extends "core/base.html" %}

{% block title %}
    <h1 style="color: blue; font-weight: bold; font-size: 24px; text-decoration: underline;">Listado de Comisiones</h1>
{% endblock title %}

{% block content %}
    <div style="margin-top: 20px;" class="py-lg-4">
        <form action="{% url 'clase:home' %}" method="get">
            <input type="text" name="consulta" placeholder="Buscar Comision...">
            <button type="submit">Buscar</button>
        </form>
    </div>
    <ul>
        {% for comision in comisiones %}
            <li>{{ comision.nombre }} | {{ comision.curso }} | {{ comision.profesor }}</li>
        {% endfor %}  
    </ul>
    <h2>Crear nueva comisión</h2>
    <form action="{% url 'clase:comision_create' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar</button>
    </form>
      
{% endblock content %}

project/Clase/templates/Clase/profesores_create.html
{% extends 'core/base.html' %}

{% block titulo %}
    Alta de Profesor
{% endblock titulo %}

{% block contenido %}
    
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <button type="submit" class="btn btn-primary">Guardar</button>
    </form>

{% endblock contenido %}

project/Clase/templates/Clase/profesores_list.html
{% extends 'core/base.html' %}

{% block title %}
<h1 style="color: blue; font-weight: bold; font-size: 24px; text-decoration: underline;">Listado de Profesores</h1>
{% endblock title %}

{% block content %}
    <div class="py-lg-4">
        <form action="{% url 'clase:profesores_list' %}" method="get">
            <input type="text" name="consulta" placeholder="Buscar profesores...">
            <button type="submit">Buscar</button>
        </form>
    </div>
    <ul>
        {% for profesor in profesores %}
            <li>{{ profesor.nombre }} {{ profesor.apellido }}</li>
        {% endfor %}
    </ul>
    <div style="margin-top: 60px;" class="py-lg-4">
        <h2>Alta Profesor</h2>
    </div>
    <form action="{% url 'clase:profesores_create' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar</button>
    </form>
{% endblock content %}