project/Clase/urls.py
from django.urls import path

from . import views

app_name = 'clase'

urlpatterns = [
    path('', views.home, name='home'),
    path('curso/create/', views.curso_create, name='curso_create'),
    path('comision/create/', views.comision_create, name='comision_create'),
    path('curso_list/', views.curso_list, name='curso_list'),
    path('estudiantes/', views.estudiantes_list, name='estudiantes_list'),
    path('estudiantes/create', views.estudiantes_create, name='estudiantes_create'),
    path('estudiantes/detail/<int:pk>', views.estudiantes_detail, name='estudiantes_detail'),
    path('profesores/', views.profesores_list, name='profesores_list'),
    path('profesores/create', views.profesores_create, name='profesores_create'),
]

project/config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('clase/', include('clase.urls')),
]

project/core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
]

project/core/models.py
from django.db import models

# Create your models here.

project/core/views.py
from django.shortcuts import render

# vistas del core
def home(request):
    return render(request, "core/index.html")

project/core/templates/core/base.html
 <!DOCTYPE html>
 <html lang="es">
 <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Adm Plataforma</title>
 </head>
 <body>
    {% block title %}
    {% endblock title %}
    
    {% block content %}
    {% endblock content %}
 </body>
 </html>

project/core/templates/core/index.html
{% extends "core/base.html" %}

{% block title %}
    <h1>Administración: Plataforma de e-learning</h1>
{% endblock title %}

{% block content %}
    <ul>
        <li><a href="{% url 'clase:home' %}">Ver Comisiones</a></li>
        <li><a href="{% url 'clase:curso_list' %}">Ver Cursos</a></li>
        <li><a href="{% url 'clase:estudiantes_list' %}">Ver Estudiantes</a></li>
        <li><a href="{% url 'clase:profesores_list' %}">Ver Profesores</a></li>
    </ul>
{% endblock content %}